name: ads_flutter
description: A new Flutter project.
homepage: https://github.com/chakery01/ads_flutter.git
version: 1.0.4
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

